FROM ultralytics/ultralytics:latest

# Install dependencies
RUN pip install numpy==1.23.5 mlflow pyyaml Ipython

RUN mkdir -p /app
RUN mkdir -p /app/datasets
# Copy the current directory contents into the container at /app
COPY app /app
WORKDIR /app
# Run app.py when the container launches
CMD ["python", "yolo_scratch_train.py"]
#m
